### ISSUE TITLE
DÚ: Zpětná vazba

### ISSUE THREAD

**Issue by EvaMach** [volakovakat/ukolnicek#1]
Ahoj Kačko, super práce. super práce! Hezky jsi oddělila komponentu Task. Nebylo to v zadání, ale příště by bylo dobré ji dát i do vlastní složky se styly. Dobře jsi použila renderTasks i fetch, kód je dobře čitelný, přehledný. Taky se mi moc líbí, jak jsi využila interpolaci a hodnotu checked ve skládání url v druhém fetchi. Tady je jenom pár drobností, jak by se to ještě dalo doupravit. :)

- řádek 2: Kratší a tradiční způsob jako destrukturovat props je přímo jako parametry funkce `export const Task = ({name, due, done}) => `Tím si pak ušetříš i získávání vlastností přes tečkovou notaci níže. 
- řádek 20: když máš zpracování dat takhle hezky ve funkci, tak jde napsat jenom `.then(renderTasks)`
- v renderTasks by stačilo jen` tasksElm.innerHTML = data.map(t => Task(t)).join('')`

**Comment by EvaMach** [comment]
A ještě super práce s ternáry v komponentě! :)

**Comment by volakovakat** [comment]
Ahoj Evi, děkuju moc za zpětnou vazbu. Kód jsem opravila dle tvých komentářů - vytvořila jsem samostatnou složku pro komponentu Task a rozdělila css. Zároveň jsem i zkrátila kód podle tvých bodů.
[https://github.com/volakovakat/ukolnicek/commits/master](url)
